apiVersion: v1
kind: Service
metadata:
  name: dual-stack-svc-require-ipv6
spec:
  ipFamilyPolicy: RequireDualStack
  type: ClusterIP
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: hello-world
